[package]
name = "todo_api"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
sqlx = { version = "0.9.0", features = [
  "postgres",
  "runtime-tokio",
  "macros",
  "time",
] }
axum = "0.8.9"
anyhow = "1.0.104"
dotenvy = "0.15.7"
time = "0.3.55"
